package application

import (
	"context"
	"time"

	"github.com/bayamasa/go-boilerplate/app/domain/user"
)

type CreateUserUsecase struct {
	userRepository user.UserRepository
}

func NewCreateUserUsecase(userRepository user.UserRepository) *CreateUserUsecase {
	return &CreateUserUsecase{
		userRepository: userRepository,
	}
}

type CreateUserInput struct {
	Email       string
	LastName    string
	FirstName   string
	Gender      string
	DateOfBirth time.Time
	Location    string
}

func (u *CreateUserUsecase) Execute(ctx context.Context, input CreateUserInput) error {
	newUser := user.NewUser(
		0, // ID will be auto-generated by the database
		input.Email,
		input.LastName,
		input.FirstName,
		input.Gender,
		input.DateOfBirth,
		input.Location,
	)

	return u.userRepository.Create(ctx, newUser)
}
