/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/tours': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 全ツアー一覧を取得
     * @description すべてのツアー情報を目的地とエリア情報と共に取得します
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description ツアー一覧の取得に成功 */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              data: {
                tour: {
                  id: number
                  title: string
                  minPriceTaxIncluded: number
                  departsAirportId: number
                  days: number
                  isDirectFlight: boolean
                  airlinesId: number
                  hotelId: number
                  thumbnailFileName: string
                }
                destination: {
                  id: number
                  name: string
                  nameJp: string
                  imageFilename: string
                }
                area: {
                  name: string
                  nameJp: string
                }
              }[]
            }
          }
        }
        /** @description サーバーエラー */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              error: string
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/destinations/:destination_id/tours': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 特定の目的地のツアー一覧を取得
     * @description 指定された目的地のツアー情報を取得します
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          destination_id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description ツアー一覧の取得に成功 */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              data: {
                tour: {
                  id: number
                  title: string
                  minPriceTaxIncluded: number
                  departsAirportId: number
                  days: number
                  isDirectFlight: boolean
                  airlinesId: number
                  hotelId: number
                  thumbnailFileName: string
                }
                destination: {
                  id: number
                  name: string
                  nameJp: string
                  imageFilename: string
                }
                area: {
                  name: string
                  nameJp: string
                }
              }[]
            }
          }
        }
        /** @description 不正なパラメータ */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              error: string
            }
          }
        }
        /** @description サーバーエラー */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              error: string
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/destinations/:destination_id/tours/:tour_id': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * ツアー詳細を取得
     * @description 指定されたツアーの詳細情報と在庫情報を取得します
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          destination_id: string
          tour_id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description ツアー詳細の取得に成功 */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              data: {
                tour: {
                  id: number
                  title: string
                  minPriceTaxIncluded: number
                  departsAirportId: number
                  days: number
                  isDirectFlight: boolean
                  airlinesId: number
                  hotelId: number
                  thumbnailFileName: string
                }
                destination: {
                  id: number
                  name: string
                  nameJp: string
                  imageFilename: string
                }
                area: {
                  name: string
                  nameJp: string
                }
                stocks: {
                  id: number
                  tourId: number
                  eventStartDate: string
                  maxCapacity: number
                  availableCapacity: number
                  createdAt: string
                }[]
              }
            }
          }
        }
        /** @description 不正なパラメータ */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              error: string
            }
          }
        }
        /** @description ツアーが見つかりません */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              error: string
            }
          }
        }
        /** @description サーバーエラー */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              error: string
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
