# このワークフローはGo言語のプロジェクトをビルドします
# 詳細は以下を参照してください: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Format Check
      run: |
        unformatted_files=$(gofmt -l .)
        if [ -n "$unformatted_files" ]; then
          echo "以下のファイルはフォーマットされていません。'go fmt'を実行してください："
          echo "$unformatted_files"
          exit 1
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
